# Default values for mechcloud_torque_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# This value should NOT be modified
torgueIngressName: torque

# Target namespace where you want to deploy this app
torqueNamespace: koyadume

# Configuration parameters for oauth2 provider
oauth2:
   clientId:
   clientSecret:
   # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
   cookieSecret:
   #remove these two parameters if you are not using github as oauth2 provider
   githubOrg: mechcloud
   githubTeam: torque
   whitelistDomain: .cloud.okteto.net

# Configuration parameters for MongoDB
mongo:
   hostPort: mechcloud-torque-mongodb:5020
   username: admin
   password: torque
   
   