# Default values for mechcloud_torque_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
# ingressAuthNamespace: ingress-koyadume
torgueIngressName: torque
torqueNamespace: koyadume
oauth2:
   clientId:
   clientSecret:
   # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
   cookieSecret:
   githubOrg: mechcloud
   githubTeam: torque
   whitelistDomain: .cloud.okteto.net
mongo:
   hostPort: mechcloud-torque-mongodb:5020
   username: admin
   password: torque