apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
type: Opaque
data:
  clientId:  {{ .Values.oauth2.clientId | b64enc }}
  clientSecret:  {{ .Values.oauth2.clientSecret | b64enc }}
  cookieSecret:  {{ .Values.oauth2.cookieSecret | b64enc }}
  