apiVersion: v1
kind: Service
metadata:
  name: mechcloud-torque-ui
  # annotations:
  #   dev.okteto.com/auto-ingress: "true"
spec:
  ports:
    - name: "5021"
      port: 5021
      targetPort: 80
  selector:
    app: mechcloud-torque-ui