apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: torque-ingress
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: mechcloud-torque-ui
          servicePort: 5021
          
          