kind: Deployment
apiVersion: apps/v1
metadata:
  name: mechcloud-torque-k8s-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mechcloud-torque-k8s-adapter
  template:
    metadata:
      labels:
        app: mechcloud-torque-k8s-adapter
    spec:
      containers:
      - name: mechcloud-torque-k8s-adapter
        image: mechcloud/mechcloud-torque-k8s-adapter:v1.2.0
        envFrom:
        - configMapRef:
            name: mechcloud-python-common-configs
        - configMapRef:
            name: mechcloud-torque-services-configs
        - configMapRef:
            name: mechcloud-torque-k8s-adapter-configs
        ports:
        - containerPort: 5000
      restartPolicy: Always
      
      