{{ if .Values.authEnabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  # annotations:
  #   dev.okteto.com/generate-host: "true"
spec:
  rules:
  - host: {{ .Values.torgueIngressName }}-{{ .Values.torqueNamespace }}{{ .Values.oauth2.whitelistDomain }}
    http:
      paths:
      - path: /oauth2
        backend:
          serviceName: oauth2-proxy
          servicePort: 4180
{{ end }}
          
          