apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mechcloud-torque-pvc1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
